# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
uid = "87d3ed1d-9912-042f-ece1-4cd70a172541eb13e82f"
type = "ui_extension"
name = "Upsell List"
handle = "upsell-list"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension's source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify's storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

[[extensions.metafields]]
namespace = "custom"
key = "upsells_in_checkout"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition



[[extensions.settings.fields]]
  key = "header_text"
  type = "single_line_text_field"
  name = "Header Text"
  description = "Text Header"

  [[extensions.settings.fields]]
  key = "add_to_cart"
  type = "single_line_text_field"
  name = "Add to cart text"
  description = "Text button"
  
  [[extensions.settings.fields]]
  key = "discount_percentage"
  type = "number_integer"
  name = "Discount Percentage"
  description = "Enter a number between 0-100 to represent discount percentage"
  
  [[extensions.settings.fields]]
  key = "remove_text"
  type = "single_line_text_field"
  name = "Remove text"
  description = "Text for remove link that appears after adding product"
  
  [[extensions.settings.fields]]
  key = "number_of_upsells"
  type = "number_integer"
  name = "Number of Upsells"
  description = "Number of upsell products to display (default: 3)"